### ISSUE TITLE
Content recognition UI suggestions

### ISSUE THREAD

**Issue by Nyhilo** [CodeTriangle/cycle-12-map#1]
When hovering over a tile, a box should be drawn around the tile to indicate that it is being hovered over. Additionally, it might be useful if the coordinates in the top left indicated the hovered tile, rather than the tile in the middle of the map.

This hover action would of course not be applicable for most mobile devices.

![image](https://user-images.githubusercontent.com/11170845/162523392-5c22cead-1f14-4b64-8c02-8e499d43b9cd.png)

After clicking or tapping on a tile, the border should change color to indicate an active state and have a line drawn between the border of the tile and the location information card to indicate the relationship between the two elements.

![image](https://user-images.githubusercontent.com/11170845/162525569-f64feb59-6213-4500-80c2-5a38afe3d0e3.png)

As a reference for the "location-to-information" connection idea, check out the 2022 reddit r/place atlas at https://place-atlas.stefanocoding.me/

**Comment by CodeTriangle** [comment]
This is something I wanted to do anyway based on my own gripes with the interface and how unclear it can be. If you want to add this on your own feel free to do so, just make sure you tell me. :)

**Comment by CodeTriangle** [comment]
I believe everything should be added that was requested.
